const fs   = require('fs');
const path = require('path');

module.exports = {
    commands: ['help', 'menu', 'start'],

    handle: async (cmd, args, msg, { sender, sendMessage, botState }) => {

        const name = botState?.botName || 'Bot';

        const help = [
            `🤖 ${name} — Command List`,
            ``,
            `🎵 Music`,
            `!play [song]  — Play a song`,
            `!search [song] — Search top 10`,
            `!skip         — Skip current song`,
            `!stop         — Stop & clear queue`,
            `!queue        — View queue`,
            `!np           — Now playing`,
            `!repeat       — Repeat song`,
            `!lyrics       — Get lyrics`,
            ``,
            `🔊 Volume`,
            `!vol [1-100]  — Set volume`,
            `!vol max      — Max volume`,
            `!vol min      — Min volume`,
            `!vol +10      — Volume up 10`,
            `!vol -10      — Volume down 10`,
            `!vol          — Show volume`,
            ``,
            `🎙️ Voice`,
            `!talkmode on  — Reply to all speech`,
            `!talkmode off — Wake word mode`,
            `!voice        — Voice status`,
            `!voiceai [on/off] — Speak AI replies over mic (hides text)`,
            `!voiceai guy  — Use male native US English accent`,
            `!voiceai aria — Use female native US English accent`,
            `!voiceai pitch baby  — Cute high-pitched voice style`,
            `!voiceai pitch giant — Deep scary voice style`,
            `!voiceai rate [fast/slow] — Speed up/down voice`,
            `!voiceai reset       — Reset all voice settings`,
            ``,
            `🤖 AI`,
            `!ai           — Enable AI mode`,
            `!quiet        — Silence bot`,
            ``,
            `💰 Economy`,
            `!daily        — Claim daily reward`,
            `!balance      — Check coins`,
            `!give [user]  — Send coins`,
            `!lb           — Leaderboard`,
            ``,
            `🎰 Gambling`,
            `!slot         — Play slots`,
            `!flip         — Coin flip`,
            `!gamble [amt] — Gamble coins`,
            ``,
            `🎁 Gacha`,
            `!gacha        — Open gacha`,
            ``,
            `🕵️ Crime`,
            `!rob          — Rob someone`,
            `!bankrob      — Rob the bank`,
            ``,
            `🛒 Shop`,
            `!shop         — View shop`,
            `!buy [item]   — Buy item`,
            `!inv          — Your inventory`,
            `!sell [item]  — Sell item`,
            `!use [item]   — Use item`,
            ``,
            `🎛️ Audio FX`,
            `!bass / !treble / !reverb`,
            `!8d / !nightcore / !slowed`,
            `!fxreset      — Reset effects`,
            ``,
            `⚔️ RPG`,
            `!hunt         — Go hunting`,
            `!heal         — Heal yourself`,
            `!adventure    — Start adventure`,
            ``,
            `🎣 Activities`,
            `!fish / !mine / !farm / !chop`,
            `(50+ grind jobs available)`,
            ``,
            `👥 Room`,
            `!who          — List users`,
            `!room         — Room info`,
            ``,
            `💡 Tip: !talkmode on to let bot hear you speak!`,
        ].join('\n');

        await sendMessage(help);
    }
};
